old_site/config/routes.rb
# frozen_string_literal: true
Rails.application.routes.draw do
  devise_for :veterans, controllers: { registrations: 'veterans/registrations', sessions: 'veterans/sessions' }
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  devise_scope :veteran do
    get :sign_up, to: 'veterans/registrations#new'
    get :join, to: 'veterans/registrations#new'
    get :login, to: 'veterans/sessions#new'
    get :sign_in, to: 'veterans/sessions#new'

    get 'profile/edit', to: 'veterans/registrations#edit'
  end

  # Split
  mount Split::Dashboard, at: 'split'

  # LetsEncrypt
  get '/.well-known/acme-challenge/:id' => 'pages#letsencrypt'
  get '/veterans/thanks', to: 'veterans#thanks'
  get '/.well-known/acme-challenge/:id' => 'pages#letsencrypt'
  resources :veterans, only: [:new, :create]
  post '/veterans/claim/:veteran', to: 'veterans#claim', as: :veterans_claim
  post '/veterans/unclaim/:veteran', to: 'veterans#unclaim', as: :veterans_unclaim

  resources :donations, only: [:index, :new, :create]

  # Maps
  get '/veterans/map', to: 'veterans#map'
  get '/maps/veterans', to: 'veterans#map'
  get '/maps/code_schools', to: 'code_schools#map'

  # Profile
  get '/profile', to: 'profile#home'
  get '/profile/mentees', to: 'profile#mentees'
  get '/profile/mentees/:mentee', to: 'profile/mentees#show', as: :profile_mentee
  post '/profile/mentees/:mentee/welcome', to: 'profile/mentees#welcome', as: :welcome_mentee
  get '/profile/edit/bio', to: 'profile#edit_bio'
  post '/profile/edit/bio', to: 'profile#update_bio'
  patch '/profile/edit/bio', to: 'profile#update_bio'
  # End Profile

  # Static pages
  get '/code_schools', to: 'code_schools#index'

  get 'about' => 'pages#about'
  get 'amazon' => redirect('https://smile.amazon.com/ch/47-4247572')
  get 'blog' => 'pages#blog'
  get 'deploy' => redirect('http://deployopcode.io/')
  get 'dwolla' => redirect('https://www.dwolla.com')
  get 'board' => 'pages#board'
  get 'contact' => 'pages#contact'
  get 'cottonbureau' => redirect('https://cottonbureau.com/products/operation-code-medal')
  get 'calendar' => 'pages#calendar'
  get 'sponsors' => 'pages#sponsors'
  get 'employers' => 'pages#employers'
  get 'events' => 'pages#events'
  get 'faq' => 'pages#faq'
  get 'founder' => 'pages#founder'
  get 'hackathons' => 'pages#hackathons'
  get 'history' => 'pages#history'
  get 'internships' => 'pages#internships'
  get 'jsguide' => 'pages#jsguide'
  get 'online' => 'pages#online'
  get 'media' => 'pages#media'
  get 'mentorship' => 'pages#mentorship'
  get 'mission' => 'pages#mission'
  get 'newgibill' => 'pages#newgibill'
  get 'military_veterans_technical_talent_pipeline' => 'pages#military_veterans_technical_talent_pipeline'
  get 'press' => 'pages#press'
  get 'privacy' => 'pages#privacy'
  get 'scholarships' => 'pages#scholarships'
  get 'square' => redirect('https://cash.me/$operationcode')
  get 'speakerrequest' => 'pages#speakerrequest'
  get 'staff' => 'pages#staff'
  get 'success_stories' => 'pages#success_stories'
  get 'action' => 'veterans#new'
  get 'fellowships' => 'pages#fellowships'
  get '/contact' => redirect('mailto:staff@operationcode.org')
  get '/flatiron' => redirect('https://learn.co/learn-together')
  get '/launchparty' => redirect('http://www.eventbrite.com/e/operation-code-launch-party-tickets-16494832488')
  get '/donate' => redirect('/donations/new')
  get '/learn' => redirect('/online')
  get '/contribute' => redirect('https://github.com/OperationCode/operationcode/blob/master/CONTRIBUTING.md')
  get '/news' => redirect('/newgibill')

  # /blog is served as a static asset from /public/blog directory, built by Jekyll

  root 'pages#home'
end

old_site/app/views/layouts/_footer.html.erb
<footer class="page-footer grey lighten-5">
  <div class="container">
    <div class="row">
      <div class="col m3">
        <h5>Who Are We</h5>
        <ul>
          <li><a href="/history">Our History</a></li>
          <li><a href="/about">About Operation Code</a></li>
          <li><a href="/faq">Frequently Asked Questions</a></li>
          <li><a href="https://medium.com/operation-code" target="_blank"></a></li>
          <li><a href="/staff">Staff</a></li>
          <li><a href="/board">Board of Directors</a></li>
        </ul>
      </div>

      <div class="col m3">
        <h5>What We Do</h2>
        <ul>
          <li><a href="/mentorship">Software Mentorship</a></li>
          <li><a href="/scholarships">Scholarship Program</a></li>
          <li><a href="/employers">Employer Services</a></li>
          <li><a href="http://deployopcode.io/">Web Application Development</a></li>
          <li><a href="mailto:schools@operationcode.org">Code School Technical Assistance</a>

        </ul>
      </div>

      <div class="col m3">
        <h5>Get Involved</h5>
        <ul>
          <li><a href="https://operationcode.threadless.com/" target="_blank">Store</a></li>
          <li><a href="https://donorbox.org/operationcode">Donate</a></li>
          <li><a href="/contribute">Open Source</a></li>
          <li><a href="/sign_up">Software Mentorship</a>
          <li><a href="mailto:staff@operationcode.org">Internships</a>
          <li><%= link_to 'Shop on AmazonSmile', amazon_path %></li>
        </ul>
      </div>

      <div class="col m3">
        <h5>Press & Media</h5>
        <ul>
          <li><a href="/press">Press Coverage</a></li>
          <li><a href="/newgibill">New GI Bill Updates</a></li>
          <li><a href="mailto:staff@operationcode.org">Press Inquiries</a>
          <li><a href="/maps/veterans">Veteran Map</a></li>
          <li><a href="/maps/code_schools">Code Schools Map</a></li>
          <li><a href="/media">Download Media</a></li>
        </ul>
      </div>
    </div>
    <div class='row'>
      <div class="col m10 offset-m1 center-align">
        <p><a href="https://www.guidestar.org/profile/47-4247572" target="_blank"><img src="https://widgets.guidestar.org/gximage2?o=9522101&l=v3" /></a></p>
        <p><em>Operation Code is a tax-exempt 501(c)(3) nonprofit organization. <a href="/privacy">Donor Privacy Policy and Refund Policy</a></em>. </br>
        <p>Proudly built with <a href="http://rubyonrails.org/">Ruby on Rails</a>, <a href="http://materializecss.com/">Materialize</a>, and maintained by the <a href="https://github.com/orgs/operationcode/people">core team</a> with the help of our <a href="https://github.com/OperationCode/operationcode/graphs/contributors">contributors</a>.<p>This site is open source. <a href="https://github.com/OperationCode/operationcode/blob/master/CONTRIBUTING.md">All pull requests welcome</a>.</p>
        <div class="social-links">
          <a href="https://twitter.com/operation_code" id="twitter" target="_blank"><i class="fa fa-twitter fa-lg"></i></a>
          <a href="https://facebook.com/operationcode.org" id="facebook" target="_blank"><i class="fa fa-facebook fa-lg"></i></a>
          <a href="https://instagram.com/operation_code" id="instagram" target="_blank"><i class="fa fa-instagram fa-lg"></i></a>
          <a href="https://www.snapchat.com/add/operationcode" id="snapchat" target="_blank"><i class="fa fa-snapchat-ghost fa-lg"></i></a>
        </div>
      </div>
    </div>
  </div>
</footer>

old_site/app/views/layouts/_header.html.erb
<ul id="about" class="dropdown-content">
  <li><%= link_to 'About Operation Code', about_path %></li>
  <li><%= link_to 'History', history_path %></li>
  <li><%= link_to 'Frequently Asked Questions', faq_path %></li>
  <li><%= link_to 'Press Coverage', press_path %></li>
  <li><%= link_to 'GI Bill Updates', newgibill_path %></li>
  <li><%= link_to 'Sponsors', sponsors_path %></li>
  <li class="divider"></li>
  <li><%= link_to 'Staff', staff_path %></li>
  <li><%= link_to 'Board of Directors', board_path %></li>
</ul>

<ul id="programs-and-services" class="dropdown-content">
  <li><%= link_to 'Software Mentorship', mentorship_path %></li>
  <li><%= link_to 'Scholarships', scholarships_path %></li>
  <li><%= link_to 'Code Schools', code_schools_path %></li>
  <li><%= link_to 'Employer Services', employers_path %></li>
  <li><%= link_to 'Web Development', 'http://deployopcode.io/' %></li>
</ul>

<div class="navbar-fixed">
  <nav class="white" role="navigation">
    <div class="nav-wrapper container">
      <%= link_to image_tag('operationcode_logo.svg'), root_path, class: 'brand-logo'%>
      <a href="#" data-activates="nav-mobile" class="button-collapse">
        <span>MENU</span>
        <i class="material-icons">menu</i>
      </a>

      <ul class="right hide-on-med-and-down">
        <li class='grey-text'><a class="dropdown-button" href="#!" data-constrainwidth="false" data-beloworigin="true" data-activates="about">About<i class="material-icons right">arrow_drop_down</i></a></li>
        <li><a class="dropdown-button" href="#!" data-constrainwidth="false" data-beloworigin="true" data-activates="programs-and-services">What We Do<i class="material-icons right">arrow_drop_down</i></a></li>

        <li><%= link_to 'Success Stories', success_stories_path %></li>
        <li><%= link_to 'Blog', '/blog', target: '_blank' %></li>
        <li>
          <a class="btn" href="https://donorbox.org/operationcode"
            data-constrainwidth="false" data-beloworigin="true" data-activates="Donate">Donate</a>
        </li>

        <% if veteran_signed_in? %>
          <li><%= link_to 'Profile', profile_path %></li>
          <li><%= link_to 'Sign Out', destroy_veteran_session_path, method: :delete %></li>
        <% else %>
          <li>
            <% ab_test(:signup_button_size, 'btn btn-large', 'btn') do |button_size| %>
            <%= link_to 'Join', new_veteran_registration_path, class: button_size, style: 'background-color: #B23900;' %>
            <% end %>
          </li>
          <% end %>
      </ul>

      <ul id="nav-mobile" class="side-nav black-text">
        <li><h6>About</h6></li>
        <li><%= link_to 'About Operation Code', about_path %></li>
        <li><%= link_to 'History', history_path %></li>
        <li><%= link_to 'Frequently Asked Questions', faq_path %></li>
        <li><%= link_to 'Press Coverage', press_path %></li>
        <li><%= link_to 'GI Bill Updates', newgibill_path %></li>
        <li><%= link_to 'Sponsors', sponsors_path %></li>
        <li class="divider"></li>
        <li><%= link_to 'Staff', staff_path %></li>
        <li><%= link_to 'Board of Directors', board_path %></li>
        <li role="separator" class="divider"></li>

        <li><h6>What We Do</h6></li>
        <li><%= link_to 'Software Mentorship', mentorship_path %></li>
        <li><%= link_to 'Scholarships', scholarships_path %></li>
        <li><%= link_to 'Code Schools', code_schools_path %></li>
        <li><%= link_to 'Employer Services', employers_path %></li>
        <li><%= link_to 'Web Development', 'http://deployopcode.io/' %></li>
        <li role="separator" class="divider"></li>

        <li><%= link_to 'Success Stories', success_stories_path %></li>
        <li><%= link_to 'Blog', blog_path %></li>
        <li role="separator" class="divider"></li>

        <a class="btn" href="https://donorbox.org/operationcode"
            data-constrainwidth="false" data-beloworigin="true" data-activates="Donate">Donate</a>

        <li role="separator" class="divider"></li>

        <% if veteran_signed_in? %>
          <li><%= link_to 'Profile', profile_path %></li>
          <li><%= link_to 'Sign Out', destroy_veteran_session_path, method: :delete %></li>
        <% else %>
          <li>
            <% ab_test(:signup_button_size, 'btn btn-large', 'btn') do |button_size| %>
            <%= link_to 'Join', new_veteran_registration_path, class: button_size, style: 'background-color: #B23900;' %>
            <% end %>
          </li>
        <% end %>
      </ul>
    </div>
  </nav>
</div>

old_site/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1.0"/>
  <meta name="description" content="Veteran-founded and led, Operation Code is a 501(c)(3) non-profit whose mission is to aid military, vets and their families learn coding and web technologies.">
  <meta name="keywords" content="operation code, veterans, software development, learn to code, keep coding, veteran coders, senate veterans, house veterans, gi bill, new gi bill, operationcode.org, #operationcode, military vets, vets">
  <meta name="author" content="Veteran Coders, for Veterans Coders">
  <meta property="og:image" content="https://static1.squarespace.com/static/586d87de725e2585df6e8448/t/5870110d6b8f5b61fdd8ee05/1483739408996/?format=500w" />
  <title>Operation Code | Open Source Veterans Non-Profit</title>

  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.7/css/materialize.min.css"></link>
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>

  <%= csrf_meta_tags %>

  <%= analytics_init if GoogleAnalytics.valid_tracker? %>
  <meta name="google-site-verification" content="nBR2ER8Hcfls6RrkC05coE9yvBWUd3Ugi-helYsZcSs" />

  <%= google_webfonts_init({
    google: ['Open Sans']
  }) %>

  <script type="text/javascript" src="assets/modernizr.js"></script>
  <script type="text/javascript" src="https://js.stripe.com/v2/"></script>
  <script type="text/javascript"> Stripe.setPublishableKey('pk_live_bqebTTza5PGXJcAAaivllE03');</script>
    <!-- Start of Async Drift Code -->
  <script>
  !function() {
    var t;
    if (t = window.driftt = window.drift = window.driftt || [], !t.init) return t.invoked ? void (window.console && console.error && console.error("Drift snippet included twice.")) : (t.invoked = !0, 
    t.methods = [ "identify", "config", "track", "reset", "debug", "show", "ping", "page", "hide", "off", "on" ], 
    t.factory = function(e) {
      return function() {
        var n;
        return n = Array.prototype.slice.call(arguments), n.unshift(e), t.push(n), t;
      };
    }, t.methods.forEach(function(e) {
      t[e] = t.factory(e);
    }), t.load = function(t) {
      var e, n, o, i;
      e = 3e5, i = Math.ceil(new Date() / e) * e, o = document.createElement("script"), 
      o.type = "text/javascript", o.async = !0, o.crossorigin = "anonymous", o.src = "https://js.driftt.com/include/" + i + "/" + t + ".js", 
      n = document.getElementsByTagName("script")[0], n.parentNode.insertBefore(o, n);
    });
  }();
  drift.SNIPPET_VERSION = '0.3.1';
  drift.load('85m6w5amcr58');
  </script>
  <!-- End of Async Drift Code -->
  <script src="https://use.fontawesome.com/3c0f7e9be1.js"></script>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  </head>
  <body>
    <%= render 'layouts/header' %>

    <div class="alert-section">
      <% flash.each do |name, msg| %>
        <%= content_tag(:div, msg, class: "alert alert-info") %>
      <% end %>
    </div>

    <%= yield %>

    <%= render 'layouts/footer' %>

    <script src="https://donorbox.org/install-popup-button.js" type="text/javascript" defer></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.7/js/materialize.min.js"></script>
    <script type="text/javascript" src="//js.hs-scripts.com/2721778.js" id="LeadinEmbed-2721778" crossorigin="use-credentials" async defer></script>
    <script>
      $(document).ready(function(){
        $(".dropdown-button").dropdown({beloworigin: true});
        $(".slider").slider({height: 528, indicators: false});
        $(".button-collapse").sideNav();
        $('select').material_select();
        // Hack until https://github.com/Dogfalo/materialize/pull/3379 is merged and on the CDN
        $('ul.tabs a').on('click', function(e){
          if($(this).attr("target") ) {
            window.location = $(this).attr("href");
          }
        });
      });
    </script>
  </body>
</html>