old_site/config/routes.rb
# frozen_string_literal: true
Rails.application.routes.draw do
  devise_for :veterans, controllers: { registrations: 'veterans/registrations', sessions: 'veterans/sessions' }
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  devise_scope :veteran do
    get :sign_up, to: 'veterans/registrations#new'
    get :join, to: 'veterans/registrations#new'
    get :login, to: 'veterans/sessions#new'
    get :sign_in, to: 'veterans/sessions#new'

    get 'profile/edit', to: 'veterans/registrations#edit'
  end

  # Split
  mount Split::Dashboard, at: 'split'

  # LetsEncrypt
  get '/.well-known/acme-challenge/:id' => 'pages#letsencrypt'
  get '/veterans/thanks', to: 'veterans#thanks'
  get '/.well-known/acme-challenge/:id' => 'pages#letsencrypt'
  resources :veterans, only: [:new, :create]
  post '/veterans/claim/:veteran', to: 'veterans#claim', as: :veterans_claim
  post '/veterans/unclaim/:veteran', to: 'veterans#unclaim', as: :veterans_unclaim

  resources :donations, only: [:index, :new, :create]

  # Maps
  get '/veterans/map', to: 'veterans#map'
  get '/maps/veterans', to: 'veterans#map'
  get '/maps/code_schools', to: 'code_schools#map'

  # Profile
  get '/profile', to: 'profile#home'
  get '/profile/mentees', to: 'profile#mentees'
  get '/profile/mentees/:mentee', to: 'profile/mentees#show', as: :profile_mentee
  post '/profile/mentees/:mentee/welcome', to: 'profile/mentees#welcome', as: :welcome_mentee
  get '/profile/edit/bio', to: 'profile#edit_bio'
  post '/profile/edit/bio', to: 'profile#update_bio'
  patch '/profile/edit/bio', to: 'profile#update_bio'
  # End Profile

  # Static pages
  get '/code_schools', to: 'code_schools#index'

  get 'about' => 'pages#about'
  get 'amazon' => redirect('https://smile.amazon.com/ch/47-4247572')
  get 'blog' => 'pages#blog'
  get 'deploy' => redirect('http://deployopcode.io/')
  get 'dwolla' => redirect('https://www.dwolla.com')
  get 'board' => 'pages#board'
  get 'contact' => 'pages#contact'
  get 'cottonbureau' => redirect('https://cottonbureau.com/products/operation-code-medal')
  get 'calendar' => 'pages#calendar'
  get 'sponsors' => 'pages#sponsors'
  get 'employers' => 'pages#employers'
  get 'events' => 'pages#events'
  get 'faq' => 'pages#faq'
  get 'founder' => 'pages#founder'
  get 'hackathons' => 'pages#hackathons'
  get 'history' => 'pages#history'
  get 'internships' => 'pages#internships'
  get 'jsguide' => 'pages#jsguide'
  get 'online' => 'pages#online'
  get 'media' => 'pages#media'
  get 'mentorship' => 'pages#mentorship'
  get 'mission' => 'pages#mission'
  get 'newgibill' => 'pages#newgibill'
  get 'military_veterans_technical_talent_pipeline' => 'pages#military_veterans_technical_talent_pipeline'
  get 'press' => 'pages#press'
  get 'privacy' => 'pages#privacy'
  get 'scholarships' => 'pages#scholarships'
  get 'square' => redirect('https://cash.me/$operationcode')
  get 'speakerrequest' => 'pages#speakerrequest'
  get 'staff' => 'pages#staff'
  get 'success_stories' => 'pages#success_stories'
  get 'action' => 'veterans#new'
  get 'fellowships' => 'pages#fellowships'
  get '/contact' => redirect('mailto:staff@operationcode.org')
  get '/flatiron' => redirect('https://learn.co/learn-together')
  get '/launchparty' => redirect('http://www.eventbrite.com/e/operation-code-launch-party-tickets-16494832488')
  get '/donate' => redirect('/donations/new')
  get '/learn' => redirect('/online')
  get '/contribute' => redirect('https://github.com/OperationCode/operationcode/blob/master/CONTRIBUTING.md')
  get '/news' => redirect('/newgibill')

  # /blog is served as a static asset from /public/blog directory, built by Jekyll

  root 'pages#home'
end

old_site/app/models/veteran.rb
# frozen_string_literal: true
# == Schema Information
#
# Table name: veterans
#
#  id             :integer          not null, primary key
#  email          :string(255)
#  first_name     :string(255)
#  last_name      :string(255)
#  service_branch :string(255)
#  zip            :string(255)
#  created_at     :datetime
#  updated_at     :datetime
#

class Veteran < ActiveRecord::Base
  belongs_to :mentor

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  EMAIL_REGEX = /\A[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]+\z/
  validates :email, format: { with: EMAIL_REGEX, message: 'Please provide a valid e-mail address' }

  geocoded_by :zip
  after_validation :geocode, if: ->(v) { v.zip.present? && v.zip_changed? }
  attr_accessor :request_mentor

  def self.lat_longs
    Veteran.where.not(zip: nil).pluck('DISTINCT latitude, longitude')
  end

  def self.unclaimed_mentees
    Veteran.where(type: nil, mentor_id: nil, wants_mentor: true)
  end

  def name
    if first_name.present? || last_name.present?
      "#{first_name} #{last_name}".strip
    else
      email
    end
  end

  def send_slack_invitation
    SlackInviterJob.perform_later(email)
  end

  def add_to_mailchimp
    MailchimpInviterJob.perform_later(
      email: email, first_name: first_name, last_name: last_name
    )
  end

  def add_to_airtables
    AddUserToAirtablesJob.perform_later(self)
  end

  def mentor?
    false
  end

  def welcome_from!(mentor)
    MenteeMailer.welcome(mentor: mentor, mentee: self).deliver_later
    update_attributes(welcomed: true, mentor: mentor)
  end
end

old_site/app/controllers/veterans/registrations_controller.rb
module Veterans
  class RegistrationsController < Devise::RegistrationsController
    def edit
      @veteran = current_veteran
      super
    end

    def create
      @veteran = Veteran.new(veteran_params)
      @veteran.password = Devise.friendly_token.first(16)
      if @veteran.save
        send_notifications
        ab_finished(:signup_button_size)
        redirect_to '/veterans/thanks'
      else
        render :new
      end
    end

    private

    def veteran_params
      params.require(:veteran).permit(:email, :zip)
    end

    def send_notifications
      # We're going to 'reset' a users password when they sign up.
      # This will send them a link to set their password and our welcome email
      @veteran.send_reset_password_instructions
      @veteran.send_slack_invitation
      @veteran.add_to_mailchimp
      @veteran.add_to_airtables
    end

    # Disables requiring a password to edit your profile
    def update_resource(resource, params)
      resource.update_without_password(params)
    end

    def after_update_path_for(_resource)
      profile_path
    end
  end
end

old_site/app/controllers/veterans/sessions_controller.rb
module Veterans
  class SessionsController < Devise::SessionsController
  end
end

old_site/app/controllers/veterans_controller.rb
class VeteransController < ApplicationController
  before_action :authenticate_veteran!, except: [:map, :thanks]

  def map
    @lat_longs = Veteran.lat_longs
  end

  def claim
    redirect_to :profile unless current_veteran.mentor?

    veteran = Veteran.find(params[:veteran])
    redirect_to(:back) if veteran.nil?

    veteran.update_attributes(mentor: current_veteran)
    redirect_to(:back)
  end

  def unclaim
    redirect_to :profile unless current_veteran.mentor?

    veteran = Veteran.find(params[:veteran])
    redirect_to(:back) if veteran.nil?

    veteran.update_attributes(mentor: nil)
    redirect_to(:back)
  end

  def thanks
    @slack_url = SlackUrl.get_url(user_operating_system)
  end

  private

  # Never trust parameters from the scary internet, only allow the white list through.
  def veteran_params
    params.require(:veteran).permit(
      :first_name,
      :last_name,
      :email,
      :zip,
      :service_branch,
      :request_mentor,
      :password,
      :password_confirmation
    )
  end
end

old_site/app/helpers/veterans_helper.rb
module VeteransHelper
  
  def service_branches
    ["Army", "Navy", "Marine Corps", "Air Force", "Coast Guard"]
  end
end

old_site/app/views/veterans/_slack_button.html.erb
<p><a class="btn btn-action" href="<%= @slack_url %>">Download Slack</a></p>

old_site/app/views/veterans/index.html.erb
<h1>Listing veterans</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @veterans.each do |veteran| %>
      <tr>
        <td><%= link_to 'Show', veteran %></td>
        <td><%= link_to 'Edit', edit_veteran_path(veteran) %></td>
        <td><%= link_to 'Destroy', veteran, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Veteran', new_veteran_path %>

old_site/app/views/veterans/map.html.erb
<h1>Veteran Map</h1>

<%= content_tag 'div', nil, id: :'veterans-map', class: :'veterans-map', data: { lat_longs: @lat_longs } %>

old_site/app/views/veterans/new.html.erb
<div class="container bs-docs-container">
  <div class="row">
    <div class="col-md-12" role="main">
      <div class="bs-docs-section">
        <p class="lead">In the United States over 200,000 computing jobs open annually and 30,000 are filled by computer science undergraduates. That number is expected to rise to 1.2 million by 2020. Meanwhile, we have 250,000 U.S. military personnel that exit the service annually, some due to sequestration. Veterans already comprise the highest unemployment across the country, over 722,000 of us.</br>

        <p class="lead">When you join our ranks you'll be joining our growing military veterans coding community. In <a href="http://operation-code.slack.com/">Slack</a>, you'll network, share resources, find job opportunities, get help with your code, and become eligible for conference scholarships and coding scholarships. Together we are Operation Code.</p>

        <!-- <p class="lead">Civilians, join us an <a href="http://operationcode.us10.list-manage.com/subscribe?u=0ab8e2b2d6c6608926c4f17d6&id=b1e19ac77b">Operation Code Ambassador</a> and then call your U.S. Senator and Member of Congress and share our efforts. -->
        </div>
    </div>
  </div>
  <%= render 'form' %>
<div>

old_site/app/views/veterans/thanks.html.erb
<div class="container">
  <div class="row">
    <div class="col m12" role="main">
      <h3  class="page-header">Thanks For Signing Up</h3>
      <p class="lead">You'll receive an e-mail and an invitation to our Slack channel shortly.</p>
      <%= render partial: "slack_button", slack_url: @slack_url if @slack_url %>
    </div>
  </div>
</div>